use crate::files::{File, FileError};
use crate::types::shared::{RequestId, Usage};
use serde::{Deserialize, Serialize};

/// A message from Claude
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct Message {
    /// Unique object identifier
    pub id: String,

    /// Object type - always "message" for Messages
    #[serde(rename = "type")]
    pub type_: String,

    /// Conversational role - always "assistant" for responses
    pub role: Role,

    /// Content generated by the model
    pub content: Vec<ContentBlock>,

    /// The model that completed the prompt
    pub model: String,

    /// The reason that generation stopped
    pub stop_reason: Option<StopReason>,

    /// Which custom stop sequence was generated, if any
    pub stop_sequence: Option<String>,

    /// Billing and rate-limit usage
    pub usage: Usage,

    /// Request ID for tracking (extracted from headers)
    #[serde(skip)]
    pub request_id: Option<RequestId>,
}

/// Extension helpers for traversing message content blocks
pub trait ContentBlocksExt {
    /// Concatenate and return all plaintext segments contained in the blocks.
    ///
    /// This is a convenience helper so that example code can simply call
    /// `msg.content.get_text()` to retrieve the full assistant response without
    /// needing to manually iterate over every `ContentBlock::Text` variant.
    fn get_text(&self) -> String;
}

impl ContentBlocksExt for [ContentBlock] {
    fn get_text(&self) -> String {
        self.iter()
            .filter_map(|b| match b {
                ContentBlock::Text { text } => Some(text.as_str()),
                _ => None,
            })
            .collect::<Vec<_>>()
            .join("")
    }
}

impl ContentBlocksExt for Vec<ContentBlock> {
    fn get_text(&self) -> String {
        self.as_slice().get_text()
    }
}

/// Conversational role
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "lowercase")]
pub enum Role {
    User,
    Assistant,
}

/// Content blocks that can appear in messages
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(tag = "type")]
pub enum ContentBlock {
    #[serde(rename = "text")]
    Text { text: String },

    #[serde(rename = "image")]
    Image { source: ImageSource },

    #[serde(rename = "tool_use")]
    ToolUse {
        id: String,
        name: String,
        input: serde_json::Value,
    },

    #[serde(rename = "tool_result")]
    ToolResult {
        tool_use_id: String,
        content: Option<String>,
        is_error: Option<bool>,
    },

    #[serde(rename = "thinking")]
    Thinking {
        /// The thinking content (may be summarized in Claude 4 models)
        thinking: String,
        /// Cryptographic signature for verification
        signature: String,
    },

    #[serde(rename = "redacted_thinking")]
    RedactedThinking {
        /// Encrypted thinking data
        data: String,
    },
}

/// Image source for image content blocks
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(tag = "type")]
pub enum ImageSource {
    #[serde(rename = "base64")]
    Base64 { media_type: String, data: String },

    #[serde(rename = "url")]
    Url { url: String },
}

/// Reasons why the model stopped generating
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum StopReason {
    EndTurn,
    MaxTokens,
    StopSequence,
    ToolUse,
}

/// Parameters for creating a new message
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MessageCreateParams {
    /// The model to use for completion
    pub model: String,

    /// Maximum number of tokens to generate
    pub max_tokens: u32,

    /// Input messages for the conversation
    pub messages: Vec<MessageParam>,

    /// System prompt (optional)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub system: Option<SystemParam>,

    /// Extended thinking configuration
    #[serde(skip_serializing_if = "Option::is_none")]
    pub thinking: Option<crate::types::shared::ThinkingConfig>,

    /// Amount of randomness (0.0 to 1.0)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub temperature: Option<f32>,

    /// Use nucleus sampling
    #[serde(skip_serializing_if = "Option::is_none")]
    pub top_p: Option<f32>,

    /// Only sample from top K options
    #[serde(skip_serializing_if = "Option::is_none")]
    pub top_k: Option<u32>,

    /// Custom stop sequences
    #[serde(skip_serializing_if = "Option::is_none")]
    pub stop_sequences: Option<Vec<String>>,

    /// Whether to stream the response
    #[serde(skip_serializing_if = "Option::is_none")]
    pub stream: Option<bool>,

    /// Tools available for the model to use
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tools: Option<Vec<crate::types::Tool>>,

    /// Tool choice strategy
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tool_choice: Option<crate::types::ToolChoice>,

    /// Additional metadata
    #[serde(skip_serializing_if = "Option::is_none")]
    pub metadata: Option<std::collections::HashMap<String, String>>,
}

/// System message parameter (can be string or structured blocks)
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum SystemParam {
    /// Simple text system prompt
    Text(String),
    /// Array of system content blocks with cache control
    Blocks(Vec<SystemContentBlock>),
}

/// System content block with optional cache control
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SystemContentBlock {
    /// The type of content block (always "text" for system)
    #[serde(rename = "type")]
    pub block_type: String,

    /// The text content
    pub text: String,

    /// Optional cache control for prompt caching
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cache_control: Option<crate::types::shared::CacheControl>,
}

impl SystemContentBlock {
    /// Create a new system text block
    pub fn text(text: impl Into<String>) -> Self {
        Self {
            block_type: "text".to_string(),
            text: text.into(),
            cache_control: None,
        }
    }

    /// Create a new system text block with cache control
    pub fn text_with_cache(
        text: impl Into<String>,
        cache_control: crate::types::shared::CacheControl,
    ) -> Self {
        Self {
            block_type: "text".to_string(),
            text: text.into(),
            cache_control: Some(cache_control),
        }
    }
}

impl From<String> for SystemParam {
    fn from(text: String) -> Self {
        Self::Text(text)
    }
}

impl From<&str> for SystemParam {
    fn from(text: &str) -> Self {
        Self::Text(text.to_string())
    }
}

impl From<Vec<SystemContentBlock>> for SystemParam {
    fn from(blocks: Vec<SystemContentBlock>) -> Self {
        Self::Blocks(blocks)
    }
}

/// A single message in the conversation
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MessageParam {
    pub role: Role,
    pub content: MessageContent,
}

/// Content for a message parameter
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum MessageContent {
    /// Simple text content
    Text(String),
    /// Array of content blocks (text, images, etc.)
    Blocks(Vec<ContentBlockParam>),
}

/// Content for tool_result content field (string or array of blocks)
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ToolResultContentParam {
    Text(String),
    Blocks(Vec<ToolResultNestedBlockParam>),
}

/// A limited set of content blocks allowed inside tool_result content
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum ToolResultNestedBlockParam {
    #[serde(rename = "text")]
    Text {
        text: String,
        /// Optional cache control for prompt caching
        #[serde(skip_serializing_if = "Option::is_none")]
        cache_control: Option<crate::types::shared::CacheControl>,
    },

    #[serde(rename = "image")]
    Image {
        source: ImageSource,
        /// Optional cache control for prompt caching
        #[serde(skip_serializing_if = "Option::is_none")]
        cache_control: Option<crate::types::shared::CacheControl>,
    },
}

/// Content block parameters for input messages
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum ContentBlockParam {
    #[serde(rename = "text")]
    Text {
        text: String,
        /// Optional cache control for prompt caching
        #[serde(skip_serializing_if = "Option::is_none")]
        cache_control: Option<crate::types::shared::CacheControl>,
    },

    #[serde(rename = "image")]
    Image {
        source: ImageSource,
        /// Optional cache control for prompt caching
        #[serde(skip_serializing_if = "Option::is_none")]
        cache_control: Option<crate::types::shared::CacheControl>,
    },

    #[serde(rename = "tool_use")]
    ToolUse {
        id: String,
        name: String,
        input: serde_json::Value,
        /// Optional cache control for prompt caching
        #[serde(skip_serializing_if = "Option::is_none")]
        cache_control: Option<crate::types::shared::CacheControl>,
    },

    #[serde(rename = "tool_result")]
    ToolResult {
        tool_use_id: String,
        content: Option<ToolResultContentParam>,
        is_error: Option<bool>,
        /// Optional cache control for prompt caching
        #[serde(skip_serializing_if = "Option::is_none")]
        cache_control: Option<crate::types::shared::CacheControl>,
    },

    #[serde(rename = "thinking")]
    Thinking {
        /// The thinking content
        thinking: String,
        /// Cryptographic signature for verification
        signature: String,
        /// Optional cache control for prompt caching
        #[serde(skip_serializing_if = "Option::is_none")]
        cache_control: Option<crate::types::shared::CacheControl>,
    },

    #[serde(rename = "redacted_thinking")]
    RedactedThinking {
        /// Encrypted thinking data
        data: String,
        /// Optional cache control for prompt caching
        #[serde(skip_serializing_if = "Option::is_none")]
        cache_control: Option<crate::types::shared::CacheControl>,
    },
}

/// Builder for creating message requests ergonomically
#[derive(Debug, Clone)]
pub struct MessageCreateBuilder {
    params: MessageCreateParams,
}

impl MessageCreateBuilder {
    /// Create a new message builder
    pub fn new(model: impl Into<String>, max_tokens: u32) -> Self {
        Self {
            params: MessageCreateParams {
                model: model.into(),
                max_tokens,
                messages: Vec::new(),
                system: None,
                thinking: None,
                temperature: None,
                top_p: None,
                top_k: None,
                stop_sequences: None,
                stream: None,
                tools: None,
                tool_choice: None,
                metadata: None,
            },
        }
    }

    /// Add a message to the conversation
    pub fn message(mut self, role: Role, content: impl Into<MessageContent>) -> Self {
        self.params.messages.push(MessageParam {
            role,
            content: content.into(),
        });
        self
    }

    /// Add a user message
    pub fn user(self, content: impl Into<MessageContent>) -> Self {
        self.message(Role::User, content)
    }

    /// Add an assistant message
    pub fn assistant(self, content: impl Into<MessageContent>) -> Self {
        self.message(Role::Assistant, content)
    }

    /// Set the system prompt
    pub fn system(mut self, system: impl Into<SystemParam>) -> Self {
        self.params.system = Some(system.into());
        self
    }

    /// Set extended thinking configuration
    pub fn thinking(mut self, budget_tokens: u32) -> Self {
        self.params.thinking = Some(crate::types::shared::ThinkingConfig::enabled(budget_tokens));
        self
    }

    /// Set extended thinking configuration with explicit config
    pub fn thinking_config(mut self, config: crate::types::shared::ThinkingConfig) -> Self {
        self.params.thinking = Some(config);
        self
    }

    /// Set the temperature
    pub fn temperature(mut self, temperature: f32) -> Self {
        self.params.temperature = Some(temperature);
        self
    }

    /// Set top_p
    pub fn top_p(mut self, top_p: f32) -> Self {
        self.params.top_p = Some(top_p);
        self
    }

    /// Set top_k
    pub fn top_k(mut self, top_k: u32) -> Self {
        self.params.top_k = Some(top_k);
        self
    }

    /// Set custom stop sequences
    pub fn stop_sequences(mut self, stop_sequences: Vec<String>) -> Self {
        self.params.stop_sequences = Some(stop_sequences);
        self
    }

    /// Enable streaming
    pub fn stream(mut self, stream: bool) -> Self {
        self.params.stream = Some(stream);
        self
    }

    /// Set tools available for the model to use
    pub fn tools(mut self, tools: Vec<crate::types::Tool>) -> Self {
        self.params.tools = Some(tools);
        self
    }

    /// Set tool choice strategy
    pub fn tool_choice(mut self, tool_choice: crate::types::ToolChoice) -> Self {
        self.params.tool_choice = Some(tool_choice);
        self
    }

    /// Set metadata
    pub fn metadata(mut self, metadata: std::collections::HashMap<String, String>) -> Self {
        self.params.metadata = Some(metadata);
        self
    }

    /// Build the message creation parameters
    pub fn build(self) -> MessageCreateParams {
        self.params
    }
}

// Convenient conversions for MessageContent
impl From<String> for MessageContent {
    fn from(text: String) -> Self {
        Self::Text(text)
    }
}

impl From<&str> for MessageContent {
    fn from(text: &str) -> Self {
        Self::Text(text.to_string())
    }
}

impl From<Vec<ContentBlockParam>> for MessageContent {
    fn from(blocks: Vec<ContentBlockParam>) -> Self {
        Self::Blocks(blocks)
    }
}

// Helper constructors for ContentBlockParam
impl ContentBlockParam {
    /// Create a text content block
    pub fn text(text: impl Into<String>) -> Self {
        Self::Text {
            text: text.into(),
            cache_control: None,
        }
    }

    /// Create a text content block with cache control
    pub fn text_with_cache(
        text: impl Into<String>,
        cache_control: crate::types::shared::CacheControl,
    ) -> Self {
        Self::Text {
            text: text.into(),
            cache_control: Some(cache_control),
        }
    }

    /// Create an image content block from base64 data
    pub fn image_base64(media_type: impl Into<String>, data: impl Into<String>) -> Self {
        Self::Image {
            source: ImageSource::Base64 {
                media_type: media_type.into(),
                data: data.into(),
            },
            cache_control: None,
        }
    }

    /// Create an image content block from base64 data with cache control
    pub fn image_base64_with_cache(
        media_type: impl Into<String>,
        data: impl Into<String>,
        cache_control: crate::types::shared::CacheControl,
    ) -> Self {
        Self::Image {
            source: ImageSource::Base64 {
                media_type: media_type.into(),
                data: data.into(),
            },
            cache_control: Some(cache_control),
        }
    }

    /// Create an image content block from URL
    pub fn image_url(url: impl Into<String>) -> Self {
        Self::Image {
            source: ImageSource::Url { url: url.into() },
            cache_control: None,
        }
    }

    /// Create an image content block from URL with cache control
    pub fn image_url_with_cache(
        url: impl Into<String>,
        cache_control: crate::types::shared::CacheControl,
    ) -> Self {
        Self::Image {
            source: ImageSource::Url { url: url.into() },
            cache_control: Some(cache_control),
        }
    }

    /// Create an image content block from a File
    pub async fn image_file(file: File) -> Result<Self, FileError> {
        if !file.is_image() {
            return Err(FileError::InvalidMimeType {
                mime_type: file.mime_type.to_string(),
                allowed: vec!["image/*".to_string()],
            });
        }

        let base64_data = file.to_base64().await?;
        Ok(Self::Image {
            source: ImageSource::Base64 {
                media_type: file.mime_type.to_string(),
                data: base64_data,
            },
            cache_control: None,
        })
    }

    /// Create an image content block from a File with cache control
    pub async fn image_file_with_cache(
        file: File,
        cache_control: crate::types::shared::CacheControl,
    ) -> Result<Self, FileError> {
        if !file.is_image() {
            return Err(FileError::InvalidMimeType {
                mime_type: file.mime_type.to_string(),
                allowed: vec!["image/*".to_string()],
            });
        }

        let base64_data = file.to_base64().await?;
        Ok(Self::Image {
            source: ImageSource::Base64 {
                media_type: file.mime_type.to_string(),
                data: base64_data,
            },
            cache_control: Some(cache_control),
        })
    }

    /// Create an image content block from a File (convenience method)
    pub async fn from_file(file: File) -> Result<Self, FileError> {
        Self::image_file(file).await
    }

    /// Create a thinking content block
    pub fn thinking(thinking: impl Into<String>, signature: impl Into<String>) -> Self {
        Self::Thinking {
            thinking: thinking.into(),
            signature: signature.into(),
            cache_control: None,
        }
    }

    /// Create a thinking content block with cache control
    pub fn thinking_with_cache(
        thinking: impl Into<String>,
        signature: impl Into<String>,
        cache_control: crate::types::shared::CacheControl,
    ) -> Self {
        Self::Thinking {
            thinking: thinking.into(),
            signature: signature.into(),
            cache_control: Some(cache_control),
        }
    }

    /// Create a redacted thinking content block
    pub fn redacted_thinking(data: impl Into<String>) -> Self {
        Self::RedactedThinking {
            data: data.into(),
            cache_control: None,
        }
    }

    /// Create a redacted thinking content block with cache control
    pub fn redacted_thinking_with_cache(
        data: impl Into<String>,
        cache_control: crate::types::shared::CacheControl,
    ) -> Self {
        Self::RedactedThinking {
            data: data.into(),
            cache_control: Some(cache_control),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_message_builder() {
        let params = MessageCreateBuilder::new("claude-3-5-sonnet-latest", 1024)
            .user("Hello, Claude!")
            .system("You are a helpful assistant.")
            .temperature(0.7)
            .build();

        assert_eq!(params.model, "claude-3-5-sonnet-latest");
        assert_eq!(params.max_tokens, 1024);
        assert_eq!(params.messages.len(), 1);
        assert_eq!(params.messages[0].role, Role::User);
        assert!(matches!(params.system,
            Some(SystemParam::Text(ref s)) if s == "You are a helpful assistant."));
        assert_eq!(params.temperature, Some(0.7));
    }

    #[test]
    fn test_content_block_creation() {
        let text_block = ContentBlockParam::text("Hello world");
        match text_block {
            ContentBlockParam::Text { text, .. } => assert_eq!(text, "Hello world"),
            _ => panic!("Expected text block"),
        }

        let image_block = ContentBlockParam::image_base64("image/jpeg", "base64data");
        match image_block {
            ContentBlockParam::Image { source, .. } => match source {
                ImageSource::Base64 { media_type, data } => {
                    assert_eq!(media_type, "image/jpeg");
                    assert_eq!(data, "base64data");
                }
                _ => panic!("Expected base64 image source"),
            },
            _ => panic!("Expected image block"),
        }
    }

    #[test]
    fn test_message_content_from_string() {
        let content: MessageContent = "Hello".into();
        match content {
            MessageContent::Text(text) => assert_eq!(text, "Hello"),
            _ => panic!("Expected text content"),
        }
    }
}
